file:
  'db/develop.sqlite3'
tables:
  - jokes:
    - name: 'joke'
      type: 'string'
      opts:
        - 'null: false'
    - name: 'score'
      type: 'float'
      opts:
        - 'null: false'
    - name: 'author'
      type: 'string'
    - name: 'is_joke'
      type: 'boolean'
      opts:
        - 'default: true'
        - 'null: false'
    - type: 'timestamps'

