file:
  'db/develop.sqlite3'
tables:
  - jokes:
    - name: 'joke'
      type: 'string'
      opts:
        - 'null: false'
    - name: 'score'
      type: 'integer'
      opts:
        - 'null: false'
    - name: 'author'
      type: 'string'
    - type: 'timestamps'

